routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\SlidersController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductsController as AdminProductsController;
use App\Http\Controllers\Admin\CategoriesController as AdminCategoriesController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\Admin\SliderController as AdminSlidersController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::prefix('admin')->middleware('auth')->group(function () {

    Route::redirect('/', '/admin/dashboard');

    Route::get('dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');

    Route::get('dashboard/{id}', [DashboardController::class, 'view'])->name('dashboard.view');

    Route::match(['get', 'post'],'dashboard/{id}/changeStatus', [DashboardController::class, 'changeStatus'])->name('dashboard.changeStatus');

    Route::get('products', [AdminProductsController::class, 'products'])->name('products');

    Route::get('products/new', [AdminProductsController::class, 'new'])->name('products.new');
    Route::post('product/new', [AdminProductsController::class, 'save_new'])->name('products.save_new');

    Route::get('products/{id}', [AdminProductsController::class, 'edit'])->name('products.edit');
    Route::put('products/{id}', [AdminProductsController::class, 'save_edit'])->name('products.save_edit');
    Route::delete('products/{id}', [AdminProductsController::class, 'delete'])->name('products.delete');


    Route::get('categories', [AdminCategoriesController::class, 'categories'])->name('categories');
    Route::get('categories/new', [AdminCategoriesController::class, 'new'])->name('categories.new');
    Route::get('categories/{category_id}', [AdminCategoriesController::class, 'edit'])->name('categories.edit');


    Route::post('categories', [AdminCategoriesController::class, 'save_new'])->name('categories.save_new');
    Route::put('categories/{category_id}', [AdminCategoriesController::class, 'save_edit'])->name('categories.save_edit');
    Route::delete('categories/{category_id}', [AdminCategoriesController::class, 'delete'])->name('categories.delete');

    Route::get('slider', [AdminSlidersController::class, 'slider'])->name('slider');
    Route::get('slider/new', [AdminSlidersController::class, 'new'])->name('slider.new');
    Route::get('slider/{id}', [AdminSlidersController::class, 'edit'])->name('slider.edit');

    Route::put('slider/{id}', [AdminSlidersController::class, 'save_edit'])->name('slider.save_edit');
    Route::post('slider/new', [AdminSlidersController::class, 'save_new'])->name('slider.save_new');
    Route::delete('slider/{id}', [AdminSlidersController::class, 'delete'])->name('slider.delete');
});

require __DIR__.'/auth.php';

Route::prefix('api')->group(function () {

    Route::get('sliders', [SlidersController::class, 'api']);

    Route::get('main-page-products', [ProductsController::class, 'mainPage']);

    Route::get('main-page-categories', [CategoriesController::class, 'api']);

    Route::get('products', [ProductsController::class, 'catalog']);

    Route::get('product', [ProductsController::class, 'viewOne']);

    Route::get('get-children-categories', [CategoriesController::class, 'getChildren']);

    Route::get('order', [OrderController::class, 'api']);
});


Route::view('/', 'index');
Route::view('catalog/{alias?}/{alias2?}', 'index');
Route::view('item/{id}', 'index')->name('item');
Route::view('wishlist', 'index');
Route::view('cart', 'index');

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable = ['parent_id', 'title', 'alias'];


    public function products()
    {
        if (request('order_by')) {
            return $this->hasMany(Product::class)->orderBy('price', request('order_by'));
        }
        return $this->hasMany(Product::class);
    }

    public function getChildrenAttribute()
    {
        return self::where('parent_id', $this->id)->get();
    }

    public function image()
    {
        return $this->hasOne(Image::class);
    }

    public function getParentAttribute()
    {
        return $this->find($this->parent_id);
    }

    public function main_page()
    {
        return $this->hasOne(MainPageCategory::class);
    }
}

app/Http/Controllers/Admin/CategoriesController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Components\Helpers;
use App\Components\ImageTable;
use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\MainPageCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Str;

class CategoriesController extends Controller
{
    public function categories()
    {
        $categories = Category::all();


        return view('categories.categories')->with('categories', $categories);
    }


    public function new()
    {
        $categories = Category::all();

        $categories_result[0] = '';

        foreach ($categories as $category) {

            $categories_result[$category->id] = $category->title;

        }

        return view('categories.view_category')->with('categories', $categories_result);
    }

    public function edit($id)
    {
        $category = Category::find($id);

        $all_categories = Category::all();

        $categories_result[0] = '';

        foreach ($all_categories as $value) {

            $categories_result[$value->id] = $value->title;
        }

        return view('categories.view_category')->with('category', $category)->with('categories', $categories_result);
    }

    public function save_new(Request $request)
    {
        $data = $request->except('_method', '_token');

        $data['alias'] = Str::slug($data['title']);

        Category::create($data);

        $inserted_id = Category::latest()->first()->id;

        $this->insertIntoMainPageProducts($inserted_id);

        return redirect()->route('categories');
    }

    public function save_edit(Request $request, $id)
    {
        $data = $request->except('_method', '_token');

        $category = Category::find($id);


        $data['alias'] = Str::slug($data['title']);

        $category->update($data);

        $this->insertIntoMainPageProducts($id);

        return redirect()->route('categories');

    }

    public function insertIntoMainPageProducts($category_id)
    {
        $row = MainPageCategory::where('category_id', $category_id)->first();

        if (\request()->hasFile('image')) {
            ImageTable::save(\request()->file('image'), $category_id, 'category');
        }

        if (\request('mainpage_category')) {
            if (is_null($row))
                MainPageCategory::create(['category_id' => $category_id]);
        } else {

            if (!is_null($row)) {
                $row->delete();
            }

        }


    }


    public function delete($id)
    {
        $category = Category::find($id);

        $category->products()->delete();

        $category->delete();

        return redirect()->route('categories');
    }
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Models\MainPageCategory;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    public function api()
    {
        $categories_ids = MainPageCategory::all();
        $output = [];

        foreach ($categories_ids as $id) {
            $target_category = $id->category;

            if ($target_category->parent_id !== 0) {
                $parent_cat = Category::find($target_category->parent_id);

                $target_category->url = 'catalog/'.$parent_cat->alias.'/'.$target_category->alias;
            } else {
                $target_category->url = 'catalog/'.$target_category->alias;
            }


            $target_category->img = $target_category->image->title ?? '';


            $output[] = $id->category;
        }

        return json_encode($output);
    }

    public function getChildren(Request $request)
    {
        $parent_category_alias = $request->input('parent_category');

        if ($parent_category_alias) {
            $parent_category = Category::where('alias', $parent_category_alias)->first();

            $children = Category::where('parent_id', $parent_category->id)->get();

            $output = $children->toArray();

            return json_encode($output);
        } else {
            $parent_categories = Category::where('parent_id', 0)->get();

            $output = $parent_categories->toArray();

            return json_encode($output);
        }


    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/categories/categories.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Менеджер категорій
        </h2>
    </x-slot>


    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 pr-10 lg:px-8">
                <div
                    class="align-middle rounded-tl-lg rounded-tr-lg inline-block w-full py-4 overflow-hidden bg-white shadow-lg px-12">
                    <div class="flex justify-between">

                        <div class="flex flex-wrap items-stretch w-full h-full mb-6 relative">
                            <div class="flex">
                                <a href="{{ route('categories.new') }}"
                                   class="mt-5 inline-block px-6 py-2 text-xs font-medium leading-6 text-center text-white uppercase transition bg-blue-700 rounded-full shadow ripple hover:shadow-lg hover:bg-blue-800 focus:outline-none">
                                    Новий пукнт меню
                                </a>
                            </div>
                        </div>

                    </div>
                </div>


                @if($categories->count() > 0)
                    <div
                        class="align-middle inline-block min-w-full shadow overflow-hidden bg-white shadow-dashboard px-8 pt-3 rounded-bl-lg rounded-br-lg">
                        <table class="min-w-full">
                            <thead>
                            <tr>
                                <th class="px-6 py-3 border-b-2 border-gray-300 text-left leading-4 text-blue-500 tracking-wider">
                                    ID
                                </th>
                                <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">
                                    Ім'я
                                </th>

                                <th class="px-6 py-3 border-b-2 border-gray-300"></th>
                            </tr>
                            </thead>

                            <tbody class="bg-white">



                                @include('categories.render_item', ['categories' => $categories, 'tab' => ''])



                            </tbody>
                        </table>


                    </div>
                @endif


            </div>
        </div>
    </div>


</x-app-layout>

resources/views/categories/render_item.blade.php
@foreach($categories as $category)

    @if($category->parent_id === 0 || !empty($tab))
    <tr>
        <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-500">
            <div class="flex items-center">
                <div>
                    <div class="text-sm leading-5 text-gray-800">
                        #{{ $category->id }}</div>
                </div>
            </div>
        </td>

        <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-500">
            <div class="text-sm leading-5 text-blue-900">{{ $tab.$category->title }}</div>
        </td>

        <td class="px-6 py-4 whitespace-no-wrap text-right border-b border-gray-500 text-sm leading-5">
            <a href="{{ route('categories.edit', $category->id) }}"
               class="px-5 py-2 border-blue-500 border text-blue-500 rounded transition duration-300 hover:bg-blue-700 hover:text-white focus:outline-none">
                Змінити ✍
            </a>
        </td>
    </tr>
    @endif

    @if(! $category->children->isEmpty())
        @include('categories.render_item', ['categories' => $category->children, 'tab' => $tab.'--'])
    @endif

@endforeach

resources/views/categories/view_category.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">

            @if(isset($category))
                Редагування "{{ $category->title }}"
            @else
                Створення нового пункту меню
            @endif
        </h2>
    </x-slot>


    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 pr-10 lg:px-8">
                <div
                    class="w-full justify-center align-middle rounded-tl-lg rounded-tr-lg inline-block w-full py-4 overflow-hidden bg-white shadow-lg px-12">

                    <form class="w-full max-w-lg"
                          action="{{ isset($category) ? route('categories.save_edit', $category->id) : route('categories.save_new') }}"
                          method="post" enctype="multipart/form-data">

                        @csrf

                        @if(isset($category))
                            {{ method_field('put') }}
                        @endif
                        <div class="flex flex-wrap -mx-3 mb-6">

                            <div class="w-full mb-8">
                                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                                       for="grid-first-name">
                                    Ім'я
                                </label>
                                <input value="{{ $category->title ?? '' }}"
                                       class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"
                                       id="grid-first-name" name="title" type="text" placeholder="Вироби з металу">
                            </div>


                            <div class="w-full mb-8">
                                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                                       for="grid-password">
                                    Батьківський пункт меню
                                </label>
                                {!! Form::select('parent_id', $categories, isset($category) ? $category->parent->id ?? '' : '', ['class' => 'border border-gray-200']) !!}
                            </div>


                            <div class="w-full mb-8">
                                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                                       for="grid-password">
                                    На головну
                                </label>

                                <input
                                       class="appearance-none block w-full bg-gray-200 text-gray-700 border border-gray-200 rounded py-3 px-4 mb-3 leading-tight focus:outline-none focus:bg-white"
                                       id="grid-first-name" name="mainpage_category" type="checkbox" {{ isset($category) && $category->main_page ? 'checked' : null }}>
                            </div>

                            <div class="w-full mb-8">
                                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2"
                                       for="grid-password">
                                    Картинка (якщо на головну)
                                </label>
                                <div class="w-full mb-8">
                                    <label
                                        class="w-64 flex flex-col items-center px-4 py-6 bg-white text-blue-500 rounded-lg shadow-lg tracking-wide uppercase cursor-pointer hover:bg-blue-500 hover:text-white">
                                        <svg class="w-8 h-8" fill="currentColor" xmlns="http://www.w3.org/2000/svg"
                                             viewBox="0 0 20 20">
                                            <path
                                                d="M16.88 9.1A4 4 0 0 1 16 17H5a5 5 0 0 1-1-9.9V7a3 3 0 0 1 4.52-2.59A4.98 4.98 0 0 1 17 8c0 .38-.04.74-.12 1.1zM11 11h3l-4-4-4 4h3v3h2v-3z"/>
                                        </svg>
                                        <span class="mt-2 text-base leading-normal">Виберіть файли</span>
                                        <input type='file' class="hidden" name="image">
                                    </label>
                                </div>

                            </div>




                        </div>

                        <div class="md:flex md:items-center">
                            <div class="md:w-1/3">
                                <button type="submit"
                                        class="inline-block px-6 py-2 text-xs font-medium leading-6 text-center text-white uppercase transition bg-blue-700 rounded-full shadow ripple hover:shadow-lg hover:bg-blue-800 focus:outline-none">
                                    Зберегти
                                </button>
                            </div>
                            <div class="md:w-2/3"></div>
                        </div>
                    </form>

                    @if(isset($category))
                        <form action="{{ route('categories.delete', $category->id) }}" method="post">
                            @csrf
                            @method('delete')

                            <button type="submit"
                                    class="mt-5 inline-block px-6 py-2 text-xs font-medium leading-6 text-center text-white uppercase transition bg-red-700 rounded-full shadow ripple hover:shadow-lg hover:bg-red-900 focus:outline-none">
                                Видалити
                            </button>


                        </form>
                    @endif

                </div>
            </div>
        </div>
    </div>





</x-app-layout>