routes/web.php
<?php

use Illuminate\Support\Facades\Route;

use App\Http\Controllers\SlidersController;
use App\Http\Controllers\ProductsController;
use App\Http\Controllers\CategoriesController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductsController as AdminProductsController;
use App\Http\Controllers\Admin\CategoriesController as AdminCategoriesController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\Admin\SliderController as AdminSlidersController;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::prefix('admin')->middleware('auth')->group(function () {

    Route::redirect('/', '/admin/dashboard');

    Route::get('dashboard', [DashboardController::class, 'dashboard'])->name('dashboard');

    Route::get('dashboard/{id}', [DashboardController::class, 'view'])->name('dashboard.view');

    Route::match(['get', 'post'],'dashboard/{id}/changeStatus', [DashboardController::class, 'changeStatus'])->name('dashboard.changeStatus');

    Route::get('products', [AdminProductsController::class, 'products'])->name('products');

    Route::get('products/new', [AdminProductsController::class, 'new'])->name('products.new');
    Route::post('product/new', [AdminProductsController::class, 'save_new'])->name('products.save_new');

    Route::get('products/{id}', [AdminProductsController::class, 'edit'])->name('products.edit');
    Route::put('products/{id}', [AdminProductsController::class, 'save_edit'])->name('products.save_edit');
    Route::delete('products/{id}', [AdminProductsController::class, 'delete'])->name('products.delete');


    Route::get('categories', [AdminCategoriesController::class, 'categories'])->name('categories');
    Route::get('categories/new', [AdminCategoriesController::class, 'new'])->name('categories.new');
    Route::get('categories/{category_id}', [AdminCategoriesController::class, 'edit'])->name('categories.edit');


    Route::post('categories', [AdminCategoriesController::class, 'save_new'])->name('categories.save_new');
    Route::put('categories/{category_id}', [AdminCategoriesController::class, 'save_edit'])->name('categories.save_edit');
    Route::delete('categories/{category_id}', [AdminCategoriesController::class, 'delete'])->name('categories.delete');

    Route::get('slider', [AdminSlidersController::class, 'slider'])->name('slider');
    Route::get('slider/new', [AdminSlidersController::class, 'new'])->name('slider.new');
    Route::get('slider/{id}', [AdminSlidersController::class, 'edit'])->name('slider.edit');

    Route::put('slider/{id}', [AdminSlidersController::class, 'save_edit'])->name('slider.save_edit');
    Route::post('slider/new', [AdminSlidersController::class, 'save_new'])->name('slider.save_new');
    Route::delete('slider/{id}', [AdminSlidersController::class, 'delete'])->name('slider.delete');
});

require __DIR__.'/auth.php';

Route::prefix('api')->group(function () {

    Route::get('sliders', [SlidersController::class, 'api']);

    Route::get('main-page-products', [ProductsController::class, 'mainPage']);

    Route::get('main-page-categories', [CategoriesController::class, 'api']);

    Route::get('products', [ProductsController::class, 'catalog']);

    Route::get('product', [ProductsController::class, 'viewOne']);

    Route::get('get-children-categories', [CategoriesController::class, 'getChildren']);

    Route::get('order', [OrderController::class, 'api']);
});


Route::view('/', 'index');
Route::view('catalog/{alias?}/{alias2?}', 'index');
Route::view('item/{id}', 'index')->name('item');
Route::view('wishlist', 'index');
Route::view('cart', 'index');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;

    protected $fillable = ['title', 'small_desc', 'category_id', 'big_desc', 'price'];

    public function images()
    {
        return $this->hasMany(Image::class);
    }

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function getCategoryNameAttribute()
    {
        $searched_cat = Category::find($this->category_id);

        if ($searched_cat->parent_id !== 0) {
            $parent_cat = Category::find($searched_cat->parent_id);
            $output = $parent_cat->title . ' -> ' . $searched_cat->title;
        } else {
            $output = $searched_cat->title;
        }

        return $output;

    }

    public function getImagesAttribute()
    {
        $images = $this->images()->get();

        foreach ($images as $image) {
            $return[] = $image->title;
        }


        return $return ?? [];
    }

    public function recommended()
    {
        return $this->hasOne(RecommendedProducts::class);
    }
}

app/Http/Controllers/Admin/ProductsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Components\Helpers;
use App\Components\ImageTable;
use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use App\Models\Product;
use App\Models\RecommendedProducts;
use Illuminate\Http\Request;

class ProductsController extends Controller
{
    public function products(Request $request)
    {
        $products = Product::orderBy('updated_at', 'desc')->paginate(25);

        if ($request->has('search')) {
            $products = Product::where('title', 'LIKE', "%{$request->input('search')}%")->orderBy('updated_at', 'desc')->paginate(35);
        }

        return view('products.products')->with('products', $products);
    }

    public function edit($id)
    {
        $product = Product::find($id);

        $categories = Helpers::get_categories_arr();

        return view('products.view_product')->with('product', $product)->with('categories', $categories);

    }


    public function new()
    {
        return view('products.view_product')->with('categories', Helpers::get_categories_arr());
    }


    public function save_new(ProductRequest $request)
    {
        $data = $request->except('_method', '_token', 'image');


        if ($request->has('image')) {

            Product::create($data);

            $inserted_id = Product::latest()->first()->id;

            foreach ($request->file('image') as $image) {
                ImageTable::save($image, $inserted_id, 'product');
            }

            $this->insertIntoRecommended($inserted_id);

        } else {
            return redirect()->back()->with('error', 'Картинку не вибрано');
        }

        return redirect()->route('products');
    }

    public function save_edit(ProductRequest $request, $id): \Illuminate\Http\RedirectResponse
    {
        $data = $request->except('_method', '_token', 'image');
        $product = Product::find($id);


        if ($request->hasFile('image')) {

            $image = $request->file('image');

            ImageTable::save($image, $id, 'product');
        }

        $product->update($data);

        $this->insertIntoRecommended($id);

        return redirect()->route('products');
    }

    public function insertIntoRecommended($product_id)
    {
        $row = RecommendedProducts::where('product_id', $product_id)->first();

        if (isset($_POST['recommended'])) {
            if (is_null($row))
                RecommendedProducts::create(['product_id' => $product_id]);
        } else {
            if (!is_null($row))
                $row->delete();
        }


    }

    public function delete($id)
    {
        $product = Product::find($id);

        $recommended = RecommendedProducts::where('product_id', $id);

        if (!is_null($recommended))
            $recommended->delete();

        $product->delete();

        return redirect()->route('products');

    }

}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Components\CollectionPaginator;
use App\Models\Category;
use App\Models\Product;
use App\Models\RecommendedProducts;
use Illuminate\Http\Request;

class ProductsController extends Controller
{
    public function catalog(Request $request)
    {
        $category = $request->input('category');
        $page = $request->input('page', 1);
        $search = $request->input('q');
        $order_by = $request->input('order_by');

        $products_per_page = 55;


        if (is_null($search)) {
            if ($category) {
                $searched_category = Category::where('alias', $category)->first();

                foreach ($searched_category->products as $product) {
                    $product->image = $product->images;

                    if (!empty($product->image)) {
                        $product->image = $product->image[0];
                    }

                    $ready_products[] = $product;
                }


                if ($searched_category->parent_id === 0) {

                    $children_categories = Category::where('parent_id', $searched_category->id)->get();

                    foreach ($children_categories as $children_category) {

                        foreach ($children_category->products as $product) {
                            $product->image = $product->images;

                            if (!empty($product->image)) {
                                $product->image = $product->image[0];
                            }

                            $ready_products[] = $product;
                        }

                    }

                }


                $output = CollectionPaginator::paginate($ready_products ?? [], $products_per_page, $page)->toArray()['data'];

            } else {
                if (!is_null($order_by)) {
                    $products = Product::orderBy('price', $order_by)->paginate($products_per_page);
                } else {
                    $products = Product::paginate($products_per_page);
                }


                foreach ($products as $product) {

                    $product->image = $product->images;

                    if (!empty($product->image)) {
                        $product->image = $product->image[0];
                    }
                    $output[] = $product;
                }
            }


        } else {
            $products = Product::where('title', 'LIKE', "%$search%")->get();

            foreach ($products as $product) {
                $product->image = $product->images;

                if (!empty($product->image)) {
                    $product->image = $product->image[0];
                }

                $ready_products[] = $product;
            }

            $output = CollectionPaginator::paginate($ready_products ?? [], $products_per_page, $page)->toArray()['data'];
        }

        return json_encode($output);
    }


    public function viewOne(Request $request)
    {
        $id = $request->input('id');

        $product = Product::find($id);

        $product->images = $product->images;

        $related = Product::where('category_id', $product->category_id)
            ->where('id', 'NOT LIKE', $product->id)
            ->limit(4)
            ->get()
            ->reduce(function ($arr, $item) {
                $item->image = $item->images;

                if (!empty($item->image)) {
                    $item->image = [$item->image[0]];
                }

                $arr[] = $item;
                return $arr;
            });

        if (is_null($related)) {
            $related = Product::all()->random(4);

            foreach ($related as $value) {
                $value->image = $value->images;

                if (!empty($value->image)) {
                    $value->image = $value->image[0];
                }

            }

        }

        $product->related = !is_null($related) ? $related : [];

        $category = $product->category;

        if ($category->parent_id !== 0) {
            $parent_category = Category::find($category->parent_id);

            $categories = $parent_category->title . ' -> ' . $category->title;
        } else {
            $categories = $category->title;
        }

        $product->categories = $categories;


        $product->reviews = [];

        return json_encode($product);
    }


    public function mainPage()
    {
        if (RecommendedProducts::count() >= 8 && Product::count() >= 8) {

            $recommended_ids = RecommendedProducts::limit(8)->get();

            /* OBJECT */
            foreach ($recommended_ids as $product_id) {
                $product = $product_id->product;

                // Якщо продукту за id не існує - удалить запис нахуй
                if (!is_null($product)) {

                    $product->image = $product->images;

                    if (!empty($product->image)) {
                        $product->image = $product->image[0];
                    }


                    $product->type = 'recommended';

                    $output[] = $product;
                } else {
                    $product_id->delete();
                }

            }

            $new_products = Product::limit(8)->orderBy('id', 'DESC')->get();

            foreach ($new_products as $new_product) {
                $new_product->image = $new_product->images ?? null;

                if (!empty($new_product->image)) {
                    $new_product->image = $new_product->image[0];
                }

                $new_product->type = 'new';

                $output[] = $new_product;
            }

        } else {
            $output = [];
        }

        return json_encode($output);
    }

}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/products/products.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            Менеджер продуктів
        </h2>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="-my-2 py-2 overflow-x-auto sm:-mx-6 sm:px-6 lg:-mx-8 pr-10 lg:px-8">
                <div
                    class="align-middle rounded-tl-lg rounded-tr-lg inline-block w-full py-4 overflow-hidden bg-white shadow-lg px-12">
                    <div class="flex justify-between">
                        <div class="inline-flex border rounded w-7/12 px-2 lg:px-6 h-12 bg-transparent">
                            <div class="flex flex-wrap items-stretch w-full h-full mb-6 relative">
                                <div class="flex">
                                    <span
                                        class="flex items-center leading-normal bg-transparent rounded rounded-r-none border border-r-0 border-none lg:px-3 py-2 whitespace-no-wrap text-grey-dark text-sm">
                                        <svg width="18" height="18" class="w-4 lg:w-auto" viewBox="0 0 18 18"
                                             fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path
                                                d="M8.11086 15.2217C12.0381 15.2217 15.2217 12.0381 15.2217 8.11086C15.2217 4.18364 12.0381 1 8.11086 1C4.18364 1 1 4.18364 1 8.11086C1 12.0381 4.18364 15.2217 8.11086 15.2217Z"
                                                stroke="#455A64" stroke-linecap="round" stroke-linejoin="round"/>
                                            <path d="M16.9993 16.9993L13.1328 13.1328" stroke="#455A64"
                                                  stroke-linecap="round" stroke-linejoin="round"/>
                                        </svg>
                                    </span>
                                </div>
                    <form>
                        <input type="text"
                               class="flex-shrink flex-grow flex-auto leading-normal tracking-wide w-full h-full flex-1 border border-none border-l-0 rounded rounded-l-none px-3 relative focus:outline-none text-xxs lg:text-xs lg:text-base text-gray-500 font-thin"
                               placeholder="Пошук..." name="search">
                    </form>



                            </div>

                        </div>
                    </div>
                    <a href="{{ route('products.new') }}"
                            class="mt-5 inline-block px-6 py-2 text-xs font-medium leading-6 text-center text-white uppercase transition bg-blue-700 rounded-full shadow ripple hover:shadow-lg hover:bg-blue-800 focus:outline-none">
                        Новий продукт
                    </a>
                </div>


                @if($products->count() > 0)
                    <div
                        class="align-middle inline-block min-w-full shadow overflow-hidden bg-white shadow-dashboard px-8 pt-3 rounded-bl-lg rounded-br-lg">
                        <table class="min-w-full">
                            <thead>
                            <tr>
                                <th class="px-6 py-3 border-b-2 border-gray-300 text-left leading-4 text-blue-500 tracking-wider">
                                    ID
                                </th>
                                <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">
                                    Заголовок
                                </th>
                                <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">
                                    Короткий опис
                                </th>

                                <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">
                                    Категорія
                                </th>

                                <th class="px-6 py-3 border-b-2 border-gray-300 text-left text-sm leading-4 text-blue-500 tracking-wider">
                                    Ціна
                                </th>

                                <th class="px-6 py-3 border-b-2 border-gray-300"></th>
                            </tr>
                            </thead>
                            <tbody class="bg-white">

                            @foreach($products as $product)
                                <tr>
                                    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-500">
                                        <div class="flex items-center">
                                            <div>
                                                <div class="text-sm leading-5 text-gray-800">#{{ $product->id }}</div>
                                            </div>
                                        </div>
                                    </td>
                                    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-500">
                                        <div class="text-sm leading-5 text-blue-900">{{ $product->title }}</div>
                                    </td>

                                    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-500">
                                        <div class="text-sm leading-5 text-blue-900">{{ Str::limit($product->small_desc, 25) }}</div>
                                    </td>


                                    <td class="px-6 py-4 whitespace-no-wrap border-b text-blue-900 border-gray-500 text-sm leading-5">
                                        <div class="text-sm leading-5 text-blue-900">{{ $product->category_name }}</div>
                                    </td>


                                    <td class="px-6 py-4 whitespace-no-wrap border-b border-gray-500 text-blue-900 text-sm leading-5">
                                        <div class="text-sm leading-5 text-blue-900">{{ $product->price }}</div>
                                    </td>


                                    <td class="px-6 py-4 whitespace-no-wrap text-right border-b border-gray-500 text-sm leading-5">
                                        <a href="{{ route('products.edit', $product->id) }}"
                                           class="px-5 py-2 border-blue-500 border text-blue-500 rounded transition duration-300 hover:bg-blue-700 hover:text-white focus:outline-none">
                                            Змінити ✍
                                        </a>
                                    </td>
                                </tr>
                            @endforeach

                            </tbody>
                        </table>

                        <div class="sm:flex-1 sm:flex sm:items-center sm:justify-between mt-4 work-sans">
                            <div>
                                <p class="text-sm leading-5 text-blue-700">
                                    Показуємо від
                                    <span class="font-medium">{{ $products->first()->id }}</span>
                                    до
                                    <span class="font-medium">{{ $products->last()->id }}</span>
                                    із
                                    <span class="font-medium">{{ $products->count() }}</span>
                                    замовлень
                                </p>
                            </div>
                            <div>
                                <nav class="relative z-0 inline-flex shadow-sm">
                                    @if($products->currentPage() > 1)
                                        <div v-if="$products.current_page > 1">
                                            <a href="{{ route('products').'?page='.($products->currentPage()-1) }}"
                                               class="relative inline-flex items-center px-2 py-2 rounded-l-md border border-gray-300 bg-white text-sm leading-5 font-medium text-gray-500 hover:text-gray-400 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100 active:text-gray-500 transition ease-in-out duration-150"
                                               aria-label="Previous"
                                               v-on:click.prevent="changePage(pagination.current_page - 1)">
                                                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                                    <path fill-rule="evenodd"
                                                          d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                                                          clip-rule="evenodd"/>
                                                </svg>
                                            </a>
                                        </div>
                                    @endif
                                    <div>
                                        @if($products->lastPage() > 1)
                                            @for($i = 1; $i <= $products->lastPage(); $i++)
                                                <a href="{{ route('products').'?page='.$i }}"
                                                   class="-ml-px relative inline-flex items-center px-4 py-2 border border-gray-300 bg-white text-sm leading-5 font-medium text-blue-700 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-tertiary active:text-gray-700 transition ease-in-out duration-150 hover:bg-tertiary">
                                                    {{ $i }}
                                                </a>
                                            @endfor
                                        @endif
                                    </div>
                                    @if($products->currentPage() < $products->lastPage())
                                        <div v-if="$products.current_page < $products.last_page">
                                            <a href="{{ route('products').'?page='.($products->currentPage()+1) }}"
                                               class="-ml-px relative inline-flex items-center px-2 py-2 rounded-r-md border border-gray-300 bg-white text-sm leading-5 font-medium text-gray-500 hover:text-gray-400 focus:z-10 focus:outline-none focus:border-blue-300 focus:shadow-outline-blue active:bg-gray-100 active:text-gray-500 transition ease-in-out duration-150"
                                               aria-label="Next">
                                                <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                                                    <path fill-rule="evenodd"
                                                          d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                                                          clip-rule="evenodd"/>
                                                </svg>
                                            </a>
                                        </div>
                                    @endif
                                </nav>
                            </div>
                        </div>
                    </div>
                @endif
            </div>
        </div>
    </div>

</x-app-layout>